# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-24 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171201_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedProfileTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_visit_profile', to=settings.AUTH_USER_MODEL)),
                ('visited_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
