# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-24 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_viewedprofiletracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewedprofiletracking',
            old_name='time',
            new_name='visited_time',
        ),
    ]
