# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-24 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180224_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewedprofiletracking',
            name='visited_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
