# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-24 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_viewedposttracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewedposttracking',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
