var MAJORS = ['Aktuerya',
'Alman Dili ve Edebiyati',
'Almanca Ogretmenligi',
'Bankacilik',
'Beslenme ve Diyetetik',
'Bilgi ve Belge YOnetimi',
'Bilgisayar Muhendisligi (Ingilizce)',
'Bilgisayar ve Ogretim Teknolojileri Ogr.',
'Biyoloji',
'Biyoloji (IO)',
'Biyoloji Ogretmenligi',
'Biyomuhendislik (Ingilizce)',
'Cografya',
'Cografya Ogretmenligi',
'Calisma Ekonomisi ve Endustri Iliskileri',
'Calisma Ekonomisi ve Endustri Iliskileri (IO)',
'cevre Muhendisligi (Ingilizce)',
'Dis Hekimligi (Ingilizce)',
'Ebelik',
'Eczacilik',
'Ekonometri',
'Ekonometri (IO)',
'Elektrik-Elektronik Muhendisligi (Ingilizce)',
'Endustri Muhendisligi (Ingilizce)',
'Endustri urunleri Tasarimi',
'Fen Bilgisi Ogretmenligi',
'Fizik',
'Fizik Ogretmenligi',
'Fizyoterapi ve Rehabilitasyon',
'Fotograf',
'Fransizca Ogretmenligi',
'Gazetecilik',
'Geleneksek Turk Sanatlari',
'Grafik',
'Halkla Iliskiler ve Tanitim',
'Hemsirelik',
'Heykel',
'Hukuk',
'Hukuk (IO)',
'Iktisat TM-1',
'Iktisat (Ingilizce)',
'Iktisat (IO)',
'Ilahiyat (%30 Arapca)',
'Ilahiyat (Ingilizce)',
'IlkOgretim Din Kulturu ve Ahlak Bilgisi Ogretmenligi',
'IlkOgretim Din Kulturu ve Ahlak Bilgisi Ogretmenligi (IO)',
'IlkOgretim Matematik Ogretmenligi',
'Ingilizce Ogretmenligi',
'Icmimarlik',
'Isletme',
'Isletme (Almanca)',
'Isletme (Ingilizce)',
'Isletme (IO)',
'Isletme Enformatigi (Almanca)',
'Isletme Fakultesi',
'Kamu YOnetimi (Fransizca)',
'Kimya',
'Kimya Muhendisligi (%30 Ingilizce)',
'Kimya Ogretmenligi',
'Makine Muhendisligi',
'Makine Muhendisligi (M.T.O.K.)',
'Makine Muhendisligi (Ingilizce)',
'Maliye',
'Maliye (IO)',
'Matematik',
'Matematik (IO)',
'Matematik Ogretmenligi',
'Mekatronik Muhendisligi',
'Mekatronik Muhendisligi (M.T.O.K.)',
'Metalurji ve Malzeme Muhendisligi',
'Metalurji ve Malzeme Muhendisligi (M.T.O.K.)',
'Metalurji ve Malzeme Muhendisligi (Ingilizce)',
'Muzik',
'Okul Oncesi Ogretmenligi',
'Okul Oncesi Ogretmenligi (IO)',
'Radyo',
' Televizyon ve Sinema',
'Rehberlik ve Psikolojik Danismanlik',
'Resim',
'Sanat Tarihi',
'Saglik YOnetimi',
'Seramik Cam',
'Sermaye Piyasasi',
'Sigortacilik',
'Sinema ve Televizyon',
'Siyaset Bilimi ve Uluslararasi Iliskiler (Ingilizce)',
'Sosyal Bilgiler Ogretmenligi',
'Sosyoloji (Ingilizce)',
'Spor YOneticiligi',
'Sinif Ogretmenligi',
'Taki Tasarimi',
'Tarih',
'Tarih Ogretmenligi',
'Tekstil',
'Turk Dili ve Edebiyati',
'Turk Dili ve Edebiyati (IO)',
'Turk Dili ve Edebiyati Ogretmenligi',
'Turkce Ogretmenligi',
'Tip (Ingilizce)',
'Zihin Engelliler Ogretmenligi',
'Zihin Engelliler Ogretmenligi (IO)']

export default MAJORS;